# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vast/home/jfarmer/summer2025/branson/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vast/home/jfarmer/summer2025/branson

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Development\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/vast/projects/opt/rhel8/x86_64/cmake/3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vast/home/jfarmer/summer2025/branson/CMakeFiles /vast/home/jfarmer/summer2025/branson//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vast/home/jfarmer/summer2025/branson/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BRANSON

# Build rule for target.
BRANSON: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BRANSON
.PHONY : BRANSON

# fast build rule for target.
BRANSON/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BRANSON.dir/build.make CMakeFiles/BRANSON.dir/build
.PHONY : BRANSON/fast

#=============================================================================
# Target rules for targets named pugixml-static

# Build rule for target.
pugixml-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml-static
.PHONY : pugixml-static

# fast build rule for target.
pugixml-static/fast:
	$(MAKE) $(MAKESILENT) -f pugixml/CMakeFiles/pugixml-static.dir/build.make pugixml/CMakeFiles/pugixml-static.dir/build
.PHONY : pugixml-static/fast

#=============================================================================
# Target rules for targets named test_buffer_exe

# Build rule for target.
test_buffer_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_buffer_exe
.PHONY : test_buffer_exe

# fast build rule for target.
test_buffer_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_buffer_exe.dir/build.make test/CMakeFiles/test_buffer_exe.dir/build
.PHONY : test_buffer_exe/fast

#=============================================================================
# Target rules for targets named test_cell_exe

# Build rule for target.
test_cell_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cell_exe
.PHONY : test_cell_exe

# fast build rule for target.
test_cell_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_cell_exe.dir/build.make test/CMakeFiles/test_cell_exe.dir/build
.PHONY : test_cell_exe/fast

#=============================================================================
# Target rules for targets named test_proto_cell_exe

# Build rule for target.
test_proto_cell_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_proto_cell_exe
.PHONY : test_proto_cell_exe

# fast build rule for target.
test_proto_cell_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_proto_cell_exe.dir/build.make test/CMakeFiles/test_proto_cell_exe.dir/build
.PHONY : test_proto_cell_exe/fast

#=============================================================================
# Target rules for targets named test_counter_rng_exe

# Build rule for target.
test_counter_rng_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_counter_rng_exe
.PHONY : test_counter_rng_exe

# fast build rule for target.
test_counter_rng_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_counter_rng_exe.dir/build.make test/CMakeFiles/test_counter_rng_exe.dir/build
.PHONY : test_counter_rng_exe/fast

#=============================================================================
# Target rules for targets named test_input_exe

# Build rule for target.
test_input_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_input_exe
.PHONY : test_input_exe

# fast build rule for target.
test_input_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_input_exe.dir/build.make test/CMakeFiles/test_input_exe.dir/build
.PHONY : test_input_exe/fast

#=============================================================================
# Target rules for targets named test_mesh_exe

# Build rule for target.
test_mesh_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mesh_exe
.PHONY : test_mesh_exe

# fast build rule for target.
test_mesh_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_mesh_exe.dir/build.make test/CMakeFiles/test_mesh_exe.dir/build
.PHONY : test_mesh_exe/fast

#=============================================================================
# Target rules for targets named test_mpi_types_exe

# Build rule for target.
test_mpi_types_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mpi_types_exe
.PHONY : test_mpi_types_exe

# fast build rule for target.
test_mpi_types_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_mpi_types_exe.dir/build.make test/CMakeFiles/test_mpi_types_exe.dir/build
.PHONY : test_mpi_types_exe/fast

#=============================================================================
# Target rules for targets named test_sampling_functions_exe

# Build rule for target.
test_sampling_functions_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sampling_functions_exe
.PHONY : test_sampling_functions_exe

# fast build rule for target.
test_sampling_functions_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_sampling_functions_exe.dir/build.make test/CMakeFiles/test_sampling_functions_exe.dir/build
.PHONY : test_sampling_functions_exe/fast

#=============================================================================
# Target rules for targets named test_imc_parameters_exe

# Build rule for target.
test_imc_parameters_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_imc_parameters_exe
.PHONY : test_imc_parameters_exe

# fast build rule for target.
test_imc_parameters_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_imc_parameters_exe.dir/build.make test/CMakeFiles/test_imc_parameters_exe.dir/build
.PHONY : test_imc_parameters_exe/fast

#=============================================================================
# Target rules for targets named test_imc_state_exe

# Build rule for target.
test_imc_state_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_imc_state_exe
.PHONY : test_imc_state_exe

# fast build rule for target.
test_imc_state_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_imc_state_exe.dir/build.make test/CMakeFiles/test_imc_state_exe.dir/build
.PHONY : test_imc_state_exe/fast

#=============================================================================
# Target rules for targets named test_photon_exe

# Build rule for target.
test_photon_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_photon_exe
.PHONY : test_photon_exe

# fast build rule for target.
test_photon_exe/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_photon_exe.dir/build.make test/CMakeFiles/test_photon_exe.dir/build
.PHONY : test_photon_exe/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BRANSON.dir/build.make CMakeFiles/BRANSON.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BRANSON.dir/build.make CMakeFiles/BRANSON.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BRANSON.dir/build.make CMakeFiles/BRANSON.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... BRANSON"
	@echo "... pugixml-static"
	@echo "... test_buffer_exe"
	@echo "... test_cell_exe"
	@echo "... test_counter_rng_exe"
	@echo "... test_imc_parameters_exe"
	@echo "... test_imc_state_exe"
	@echo "... test_input_exe"
	@echo "... test_mesh_exe"
	@echo "... test_mpi_types_exe"
	@echo "... test_photon_exe"
	@echo "... test_proto_cell_exe"
	@echo "... test_sampling_functions_exe"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

